### ISSUE TITLE
How to access column names for `grounding_terms.tsv`?

### ISSUE THREAD

**Issue by dhimmel** [indralab/gilda#60]
I'd like to do some analyses on the terms in gilda. However, `gilda.grounder.load_terms_file` returns a lookup dictionary rather than a list of terms in `grounding_terms.tsv`.

When I use pandas to read the table like `pd.read_table(gilda.resources.get_grounding_terms())`, the resulting dataframe doesn't have column names.

I think the column names are specified at 

https://github.com/indralab/gilda/blob/8e5fd672455388c8bac178b98f13604876581f3f/gilda/term.py#L25-L32

The problem is that I don't see how to access those at the Term class level, and instead only on a Term instance. So possible solutions would be to:

1. add a header row to the TSV (not sure if you can make back incompatible changes in future releases)
2. define these fields at the Term class level (inheriting from pydantic or dataclasses would help)

**Comment by dhimmel** [comment]
Here's a temporary solution (but not ideal for users to hardcode the column names):

```py
col_names = ['norm_text', 'text', 'db', 'id', 'entry_name', 'status', 'source', 'organism']
pd.read_table(gilda.resources.get_grounding_terms(), names=col_names)
```

**Comment by bgyori** [comment]
This is the function which serializes a Term into a row that is then written into the TSV:
https://github.com/indralab/gilda/blob/8e5fd672455388c8bac178b98f13604876581f3f/gilda/term.py#L57-L61, you can see the order here. For future users who may be interested in looking directly at the resource file, it should be possible to simply add column names to the TSV file in the next release (since resource files are pinned to specific versions, compatibility will not be an issue).
